#pragma once

#include <core/reflection/Action.h>
#include <core/reflection/Attribute.h>
#include <core/reflection/DelegateAction.h>
#include <core/reflection/DelegateValue.h>
#include <core/reflection/IModifiableValue.h>
#include <core/reflection/IReadableValue.h>
#include <core/reflection/ISerializable.h>
#include <core/reflection/ITypedModifiableValue.h>
#include <core/reflection/ITypedReadableValue.h>
#include <core/reflection/MemberInfo.h>
#include <core/reflection/MethodAction.h>
#include <core/reflection/MethodAdapter.h>
#include <core/reflection/MethodInfo.h>
#include <core/reflection/PropertyAdapter.h>
#include <core/reflection/PropertyInfo.h>
#include <core/reflection/PropertySetInfo.h>
#include <core/reflection/ReferenceValue.h>
#include <core/reflection/Reflection.h>
#include <core/reflection/Type.h>
#include <core/reflection/TypedProperty.h>
#include <core/reflection/TypedPropertySetInfo.h>
#include <core/reflection/ITypedSerializableValue.h>
#include <core/reflection/MemberAdapter.h>